### ISSUE TITLE
Lot's of syntax errors

### ISSUE THREAD

**Issue by Skyladd** [TKRT-Creations/SkyBlockXT#25]
Fixing the one on line 47 just lead to more syntax errors, not sure if this is an issue with php7 or not but everything is becoming php7 now, so id start coding for it if i were you. :)

**Comment by SkygridRex** [comment]
Bah! Blame developers

**Comment by TheKillerTacos** [comment]
:(  But anyways, its moslty PHP5, Im going to finish PHP5 then make PHP7 Branch,

**Comment by TheKillerTacos** [comment]
WTF, im getting new notifs about this email...
