### ISSUE TITLE
[Confution] Stole some of my code... 

### ISSUE THREAD

**Issue by Blubberboy333** [TKRT-Creations/SkyBlockXT#28]
You know, this plugin looks similar to the SkyBlock plugin that I made... It's just in other languages. If you look in the plugin.yml file, you'll see that the permissions are nothing like the permissions set in the plugin. But the permissions in the plugin are the permissions that I made! This is looking kinda suspicious. 
My Plugin:
https://github.com/Blubberboy333/SkyBlock
Someone else take a look at this and let me know what you think. I think they stole some of my code...

**Comment by TheKillerTacos** [comment]
Yep, I saw Linuzo SkyBlock Plugin, I  think he is still mentioned on Credits.md. so.

**Comment by Blubberboy333** [comment]
Another thing, If you download the latest release, it is EXACTLY my code, just in Spanish

**Comment by TheKillerTacos** [comment]
yep, Before this plugin was Modified for my Personal use, the I decided to update it, so the release is now obsolete, i want to delete those releases, but idk how,.

**Comment by Blubberboy333** [comment]
Oooooh, I see now, he forked my project to his account and made it spanish

**Comment by TheKillerTacos** [comment]
Nope, he had the plugin, then i translated it, for my Servers, then i found out it didnt work and started to update it, then some people said that they found this plugin and hoping it to make it work, then i decided to make this bigger, so here are we now

**Comment by Blubberboy333** [comment]
Oh ok

**Comment by TheKillerTacos** [comment]
I can include you in this Project if you want to, and also ill add You to credits.md

**Comment by SkygridRex** [comment]
But as outside collaborator

**Comment by Blubberboy333** [comment]
Sure, I'd like that. I can also help you update this plugin into a fully functional plugin

**Comment by TheKillerTacos** [comment]
ok, right now im Making the plugin load, since it wasnt, now it works, just fixing generator, and also How do i save resources! since the one in the code (See latest Commit on Main.php) is crashing the plugin (Not the server anymore)

**Comment by SkygridRex** [comment]
This: { crash the server

**Comment by TheKillerTacos** [comment]
not anymore, fixed. test it on pmt.mcpe.me (Phar builder)

**Comment by Blubberboy333** [comment]
@TheKillerTacos It depends on what kind of resource you want to save.. Do you want to save a new config?

**Comment by SkygridRex** [comment]
I always test this with DevTools

**Comment by TheKillerTacos** [comment]
Save the lang file, im looking on in the Pocketmine Documentation

**Comment by SkygridRex** [comment]
@TheKillerTacos can you give me basic write permissions in ALL REPOSITORIES?

**Comment by TheKillerTacos** [comment]
Wait
and i just found out how to save resources, it didnt need plugin->.

**Comment by SkygridRex** [comment]
I saw his repo and he steal code from linuzo

**Comment by TheKillerTacos** [comment]
idk who made the code, but Please now go to gitter, I dont like  to make chats on issues;

Login with github https://gitter.im/TKRT-Creations/SkyBlockXT
