### ISSUE TITLE
[CRITICAL]  Call to a member function get() 

### ISSUE THREAD

**Issue by TheKillerTacos** [TKRT-Creations/SkyBlockXT#30]
[CRITICAL] Need fix or plugin development may slow down/Stop!!
=======================================================
* Error on line 65, 
* Error Message: Fatal error: Call to a member function get() on resource
* Full Error Message: Fatal error: Call to a member function get() on resource in phar://C:/Users/#####/Desktop/CS/plugins/SkyBockXT.phar/src/SkyBlockXT/Main.php on line 65

Code:
--------
###########################################
60		if($this->getConfig()->get("EnableDebug") == true){
61			$this->getLogger()->notice(TextFormat::GREEN . "[DEBUG] Islands and player" .$tkrt);
62		}
63		// End of File/Folder Creation
64
65		$info_pluginloaded = $this->getResource("/Lang-".$defLang.".yml")->get("INFO.PluginLoaded"); 
66		$this->getLogger()->info(TextFormat::BLUE . $msg_pluginloaded);
67
68			if($this->getConfig()->get('EnableUUID') == true){
69			$UUID_Data = $this->getConfig()->get("Language") + $this->getConfig()->get("IslandPerWorld") + $this->getServerName();
70			$hash = crypt($UUID_Data);
############################################

My tought of this error:
Plugin cant "get->" on resource, maybe it doesnt finds it? or am i forgetting to import something?

Solution: IDK!

**Comment by TheKillerTacos** [comment]
@Blubberboy333 @SkygridRex @AndreTheGamer @Skyladd

**Comment by Blubberboy333** [comment]
I'll try to fix this

**Comment by Blubberboy333** [comment]
I think i might have fixed it, but i haven't tested it

**Comment by TheKillerTacos** [comment]
Ok, ill test it out, just that i tried fixing it but it just gave blank output...

**Comment by SkygridRex** [comment]
I could test it

**Comment by TheKillerTacos** [comment]
Well, plz do it, im Going to start with the generator.

**Comment by SkygridRex** [comment]
Tested line 280 cause crash

**Comment by SkygridRex** [comment]
In main.php

**Comment by TheKillerTacos** [comment]
What does it says? and with what did you tested? CS, IM, Genesys? Also i'm Updating it, i get:

[21:13:26] [Server thread/CRITICAL]: ClassNotFoundException: "Class SkyBlockXT\Tools\FileConfig not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 128

Let  me just Commit this and you can see if i placed anything wrong :(

**Comment by SkygridRex** [comment]
CS

**Comment by SkygridRex** [comment]
I need more info

**Comment by TheKillerTacos** [comment]
Try testing it now, Compile this and See if you can fix [FileConfig](https://github.com/TKRT-Creations/SkyBlockXT/blob/master/src/SkyBlockXT/Tools/FIleConfig.php/) since its giving **Class not Found** While Loading plugin.

**Comment by TheKillerTacos** [comment]
Im Going to test out Travis-CI, or use jenkins, ill start making the skyblockxt.tk...

**Comment by SkygridRex** [comment]
Try Now 
https://github.com/TKRT-Creations/SkyBlockXT/commit/7dd40725185ba2277d0a6b91fbe97a22cba3546d

**Comment by TheKillerTacos** [comment]
New Error:
Fatal error: Call to undefined method SkyBlockXT\Main::FileConfigs() in phar://C:/Users/XXXXX/Desktop/ClearSky/plugins/SkyBockXT.phar/src/SkyBlockXT/Main.php on line 34

So i fixed FileConfig (Syntax errors), and also changed the namespace to namespace SkyBlockXT\Tools; from FileConfig.php and now it crashed :(

**Comment by MCPEPIG** [comment]
I made a pull request to fix newest error

**Comment by TheKillerTacos** [comment]
Merged,

**Comment by TheKillerTacos** [comment]
Closing, MultiLanguage Support will be Placed on later,
