### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by AdversariusPE** [TKRT-Creations/SkyBlockXT#31]
The Plugin does not working on my Server! It is enabled but if I type any commands of /is, nothing does. Sorry for my Bad English, I'm German. 

Genisys, PHP7

**Comment by SkygridRex** [comment]
This plugin not works with php 7 use ClearSky because works with PHP 5

**Comment by TheKillerTacos** [comment]
And also im working on this, Cant debug it, still needs fixing, and its PHP5
