### ISSUE TITLE
[TODO] PHP7 support (Plz add php7 support)

### ISSUE THREAD

**Issue by Adam1609** [TKRT-Creations/SkyBlockXT#33]
Can u upgrade to php7, because Genisys r over good this stuff

**Comment by SkygridRex** [comment]
Ok i will work in that

**Comment by Blubberboy333** [comment]
I don't see why this plugin won't work with php7. From what I can tell, it's not ready to be used in any version of pocketmine of php

**Comment by TheKillerTacos** [comment]
This is more buggy than pocketmine its self! xD

**Comment by SkygridRex** [comment]
One day this will be fixed

**Comment by TheKillerTacos** [comment]
"One Day"

**Comment by SkygridRex** [comment]
What?

**Comment by TheKillerTacos** [comment]
"One day", Algun dia, Someday ill fix this :(, anyways, i had been inactive since my HDD Got damaged and just change it to a new one, added a SDD, another HDD, and New HDD for OS, all on my ZBook! :D

**Comment by SkygridRex** [comment]
Well

**Comment by TheKillerTacos** [comment]
#39

**Comment by SkygridRex** [comment]
Following #43 This issue will be closed

**Comment by TheKillerTacos** [comment]
SEEE YA ALL ON POCKET PROJECTS!

**Comment by TheKillerTacos** [comment]
3

**Comment by TheKillerTacos** [comment]
2

**Comment by TheKillerTacos** [comment]
1
