### ISSUE TITLE
[INFO FOR DEVS] Language will Temporaly load on config.yml

### ISSUE THREAD

**Issue by TheKillerTacos** [TKRT-Creations/SkyBlockXT#34]
So it will be easier to use MultiLang to run on local Config.yml, So, we will use that by now, just that when it loads the plugin, the language will be used, then if User changes the Lang, it will change the Lang and then the plugin will load old config and rename it, then it will get the Config to be merged to new Config.yml, so only Language Section changes, ill do a PR With everything.

This is temporal, When we found out how to use MultiLang, we will switch to that, We may also look at
other plugins with MultiLang

**Comment by SkygridRex** [comment]
Nooooooo

**Comment by TheKillerTacos** [comment]
#35

**Comment by TheKillerTacos** [comment]
#35
