### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Blubberboy333** [TKRT-Creations/SkyBlockXT#38]
What I do on my server, is use [EmptyWorld](https://github.com/Muirfield/pocketmine-plugins/tree/master/EmptyWorld) by @alejandrolui to create an empty world. The empty worlds are the ones that I use for SkyBlock

**Comment by TheKillerTacos** [comment]
Had you checked out the README.md from Tools? Here a [Link](https://github.com/TKRT-Creations/SkyBlockXT/blob/master/src/SkyBlockXT/Tools/README.md#skyworld-mod-from-emptyworld)
