### ISSUE TITLE
[PHP7] Upgrading to PHP7

### ISSUE THREAD

**Issue by TheKillerTacos** [TKRT-Creations/SkyBlockXT#39]
PHP7
======
>SO I JUST ADDED ALMOST EVERY LABEL!

Hey! It's time to Upgrade to PHP7!,
Since PHP5 seem to be Now Deprecated on PocketMine (and Forks), and 
by now the only Fork (That I had Seen) that support PHP5 is ClearSky,
and by recent Commits on PHP7, it seems like they will now start on PHP7 anytime soon,

So By now, We should be Starting to Update the Plugin to PHP7,

@Blubberboy333 @SkygridRex @AndreTheGamer @Skyladd & @TheKillerTacos

**Comment by SkygridRex** [comment]
Venga ya usemos eclipse

**Comment by TheKillerTacos** [comment]
Yo uso Code, de Visual Studio, y Visual Studio,

**Comment by TheKillerTacos** [comment]
DELETING PLUGIN: RECODING FROM SCRATCH SOON

- TKRT
