### ISSUE TITLE
Php7 not work 

### ISSUE THREAD

**Issue by Thecraftdu34** [TKRT-Creations/SkyBlockXT#41]
not work php7. It's time to update to php7 !! Error: "Call to a member function get() on resource" (EXCEPTION) in "/phar_SkyBlockXT-master (1)_c2GJ7NXpuD4EVOM.phar/src/SkyBlockXT/Main" at line 66[m

**Comment by SkygridRex** [comment]
PHP 7 works but not the commands

**Comment by TheKillerTacos** [comment]
Plugin will be Rewritten from scratch, Again badly, ill start coding the base code maybe on July 20, when i finish the base for PocketStats and CraftPanel Advance.

**Comment by SkygridRex** [comment]
I Don't understand what is happing
